### ISSUE TITLE
feature: add automatic GM3 plugin Build

### ISSUE THREAD

**Issue by xxpasixx** [xxpasixx/pam-osc#10]
[https://github.com/bootsie123/ma3-plugin-action](https://github.com/bootsie123/ma3-plugin-action)

**Comment by bootsie123** [comment]
Let me know if you'd like me to create a PR for this! I'm assuming for now the simplest setup would be having it run on push when in a PR and then filtering based on changes to lua files

**Comment by xxpasixx** [comment]
That would be awsome 😄 

i just saw it on your gitub and thouhgt i need to take a look at this

**Comment by bootsie123** [comment]
Can do! After manually exporting the plugin from MA3 a few times while I was working on my other PR, I decided enough was enough and I'd just automate it 😄

**Comment by thomaas351** [comment]
Bonjour je n'arrive pas à l'ajouter sur mon PC cela eest un peu complexe pouvais vous m'aider...

**Comment by xxpasixx** [comment]
Thanks for that, it makes live way easyer 😄
