### ISSUE TITLE
Encoder im normalen Mode der X-Touch Compact für Attribute nutzen

### ISSUE THREAD

**Issue by Patrick-MA3** [xxpasixx/pam-osc#13]
Für die große X-Touch können über die Encoder Attributwerte wie Dimmer, RGB_R, Pan, Tilt und co. angesteuert werden, das alles geschieht im MC-Mode. Die Compact ist allerdings im normalen Mode programmiert, da im MC-Mode die Encoder 9-14 anscheinend nicht richtig abgegriffen werden können und 15 und 16 fehlerhafte Midi-Befehle aussenden.

Gibt es eine Möglichkeit, die Dimmer-Werte und co. auch im normalen Mode auf dem X-Touch Compact über die Encoder anzusteuern? Bei meinen bisherigen Versuchen bin ich immer wieder auf das Problem der absoluten Werte gestoßen, es wird also immer nur etwas auf den Attributwert addiert, oder bei Veränderung der Skala erst nach sehr viel Drehen endlich die andere Drehrichtung umgesetzt.

**Comment by xxpasixx** [comment]
Hey Patrick,

ich hab die funktionalität jetzt auch in den normalen xTouchCompact eingebaut.

!Wichtig!
Man muss dazu das Mapping in der XTouch Software aktuallisieren und den Device Namen in OpenStageControl abändern:
[Mapping](https://github.com/xxpasixx/pam-osc/wiki/xTouchCompactRltv1-%E2%80%90-Playback-&-Encoders)

Sollte was nicht klappen einfach nochmal nen Ticket auf machen oder aufm Discord fragen stellen.



Hey Patrick,
i got the function working to controll the Attributes with the Encoders with the normal xTouch Compact.

!!! Important !!! 
You need to set the Configuration in the XTouch Editor software new and change the device Name in OpenStageContro.
Take a look at the new Mapping: [Mapping](https://github.com/xxpasixx/pam-osc/wiki/xTouchCompactRltv1-%E2%80%90-Playback-&-Encoders)


If You have any questions create a Ticket or just ask on the [Discord ](https://github.com/xxpasixx/pam-osc/wiki)

**Comment by Patrick-MA3** [comment]
Hey,

ich habe die Funktionen getestet und es klappt super. Inzwischen bin ich auf die große Behringer umgestiegen und finde deine Einbindung über das große Jogwheel sehr gelungen!
