### ISSUE TITLE
what customisations for the large x touch with the large wheel

### ISSUE THREAD

**Issue by deltapirat** [xxpasixx/pam-osc#2]
Hi, I'm so glad that someone finally wrote such code. 
I have the big X-touch with the big wheel. 
Can you provide the code for that too? 
The code is intended for the compact. 
I set your code using the instructions, but the faders on the x-touch don't move either. 
Once you understand how to edit the whole thing, it will certainly be easy to add color to the buttons etc. 
I would be very grateful to you. 
Best regards Beni

**Comment by Dogo69Dog** [comment]
Hey, ive gotten it to work using Chataigne. Lmk if your open to use that, I havent gotten it to work using open stage tho.

**Comment by deltapirat** [comment]
Hey, yes I use champaigne. I was able to modify your script in an amateurish way so that my faders work on the big X-touch in MA3. However, I can't control sequences or macros directly via the "Open Stage Control" path to MA3, at least I haven't found out yet. If you have a ready-made parameterization on Champaigne, I would be happy to test it for you. I'm not good at programming code. I would rather deal with lights. Even if I now send parallel midi signals to the X-Touch software, they suddenly no longer arrive. Does it have something to do with Ctrl absolute/relative? So I would have to do everything via OSC. But I would also have to be able to control sequences, macros, speedmasters etc. directly. And how exactly do I control the button feedback of the knobs?

**Comment by Dogo69Dog** [comment]
I haven’t made a advanced file in chataigne. I actually never gotten it to work with open stage control so do you mind sending the config you have on open stage control and ma3 and the modules file. It would get input but when I move something in ma3 it won’t output to my x touch

**Comment by xxpasixx** [comment]
Hey deltapirat,
sorry for the late response, i was on Vaccation for a vew Weeks.
Thanks for testing it out.

I could try to add a config for the BigXTouch, but i don't have one, so you woud need to test it then for me.
For the Big Wheel, would you like to controll for example the Dimmer Value with that ? thats one of my todos that you would be able to do these kind of things, but currently im not able to do this. If you want to use it as a normal fader, i would need to check what midi signals are behind this, maybe i could get it to work :)

for the colours, i realy like to have the colour from MA be able to represend it on the XTouch, but at the moment i didn't had the time and need to figgure it out how it works. let me see what i can do.

If you want to run for example Macros or Speed faders, you just have to assign them on the Executer that is assigned to the Button of the XTouch.

Let me knew if you are still interested in the configuration for the big XTouch and i will see what i can do for you.

Have a great day :)

**Comment by deltapirat** [comment]
hi, yes I'm still interested. I'll find you the midi signals of the big wheel. But I will also try to use your existing script to control macros/sequences via detours. I'll get back to you.
Thanks a lot

**Comment by xxpasixx** [comment]
hey @deltapirat,
i have borrowed a xTouch from a Friend and created a config for it in the new Version 1.
It is still in **development** and not 100% error Free!
you can check it out on: [https://github.com/xxpasixx/pam-osc/tree/v1](https://github.com/xxpasixx/pam-osc/tree/v1)
The setup Doku can be found here: [https://github.com/xxpasixx/pam-osc/wiki/Setup](https://github.com/xxpasixx/pam-osc/wiki/Setup) also the Doku is not fully ready yet.

if you want to try it out and give some feedback / errors would be great :)

PS: there is also a mapping of the Displays and colors in it 😄

**Comment by deltapirat** [comment]
wow that's great. I will be very happy to test it for you. Just give me a few days or a week, then I can write you everything you need to know. Thank you very much for your work!

**Comment by xxpasixx** [comment]
Hey @deltapirat,
can you may help me with something ? Can you provide me the numbers for the empty buttons ?
i needed to return the xTouch and forgott to write down the midi notes of the missing buttons.
That would be awsome. Thank you :)

<img width="760" alt="xTouch1Mapping" src="https://github.com/xxpasixx/pam-osc/assets/62435140/14bd8039-750a-4bfb-ab26-54789527f4f3">

**Comment by deltapirat** [comment]
Hi, I'd be happy to help you. Sorry if there are always delays in my replies. I have a lot to do. I will try to give you the missing midi mappings. If I have any problems, I'll get back to you.
Maybe something else: I wanted to test the script you made for the big x-touch. 
Here are a few questions:
1. what mode does the x-touch need to be set to? 
2. you have created several script files. Where does all this code have to go? I load a file (pam-OSC-Module.js) into Open Stage Control, the script "pam-OSC.lua" as a plugin into the MA3 software. Where does the rest go? 
Best regards from Hamburg

Translated with DeepL.com (free version)

**Comment by deltapirat** [comment]
Here is perhaps another interesting video about the colors. Maybe it will help you:
https://www.youtube.com/watch?v=5J3JjWTXi64

Is this perhaps the midi mapping card you are looking for? I won't be home until tonight
https://www.azslow.com/files/mcu.png

**Comment by Dogo69Dog** [comment]
It doesent have the midi keys in the image, also to answer your first question: you need to be in midi mode not mc mode

**Comment by xxpasixx** [comment]
🇩🇪 
Servus @deltapirat,
Grüße vom Bodensee ;)
Kein problem, ich kenns. manchmal is viel los. Vielen dank für das Bild mit dem Mapping, das hilft schonmal sehr. 
Hab das irgendwie nicht gefunden. Du musst mir die Mappings also nicht nochmal raussuchen.

1. das xTouch (also das Große) muss in den MC mode, anders als @Dogo69Dog geschrieben hat. Das gilt nur für das xTouchCompact.
2. Ich hab hier ne Anleitung auf englisch, die die Schritte erklärt: [Anleitung](https://github.com/xxpasixx/pam-osc/wiki/Setup)
Die Bilder da drin sind leider nicht aktuell. werden bald aktuallisiert.

Das pam-OSC-Module.js kommt in OpenStageControl als Custom Module.
In das Feld Send kommt deine IP:Port, also `127.0.0.1:9003`
Bei midi musst du schaun auf welchem port das ist, wenn du kein anderes Gerät angeschlossen hast, dann `xTouch1:0,1`
Dann gehst du auf Play.

in MA kannst du mitlerweile einfach nur die Datei in deinen MA plugins ordner kopieren. also von `pam-osc/gma3_library` nach `C:\ProgramData\MALightingTechnology\gma3_library`.
Dann gehst du in plugins Pool, machst nen neues und gehst auf Import.

Und du musst in MA in einer session sein und die OSC configuration richtig haben: [Wie hier auf dem Bild](https://github.com/xxpasixx/pam-osc/wiki/Setup#configure-in----osc)

Sollteste weitere Fragen haben, kannst auch bei uns aufn Discord kommen. Ist noch nicht fertig, aber dann können wirs uns bei dir anschauen :) [https://discord.gg/VjtdepNb](https://discord.gg/VjtdepNb)

**Comment by xxpasixx** [comment]
So, the new Version is out with the support for the xTouch.
If something dont't work just open a new Issue. will close this now :)
