### ISSUE TITLE
only a Question

### ISSUE THREAD

**Issue by PixelLighting** [xxpasixx/pam-osc#5]
Hello i wanted to ask how in some details this works ?

Does it work Page undependant ? i use my Xtouch COmpact Page Bank A fader 1 thru 8 Page B 9 Thru 15 and the master is the master Dimmer. and the Buttons on the Side to Change the Page i want to go.

I mainly using Chataigne for mapping because i use an Xtouch Mini for the X Buttons like on the Console its the exact layout and an Akai Apc Mini mk2 for Flash effects and my Main Dimmer Fader so like using another Software like OpenStageControll would add an extra Fault Point in my System to just add a bit more feedback then i know have, is it maybe possible that you write the same Plugin like a Chatagine Module.

i using a ma3 Plugin that i modified myself a bit that sends midi out of ma to my Xtouch where the Fader and my Encoders are having feedback the modified part is that the Encoder have Feedback too, you just need to set the led Ring behaviour with the Editor from Behringer itself to Pan so you get the Filling up Led Ring.

The latest 2.0 update only increased the OSC Buffer inside ma so if this is a 1.9.7.0 Plugin it still should work and very small changes in LUA workflow

**Comment by xxpasixx** [comment]
hey @PixelLighting
this setup is build to work on the Current Page of MA.
So yes, you can modify the buttons to change the Page in MA, and then it automaticly moves the Faders.
I would not recomend you to use chatainge and OSC at the same time. as you sayed this just adds more points of failiure.
Currently i have a lot more things i want to add to the pam-osc, so i dont want to develop something for chataine at the moment.

Is there anything i could help you out with pam-osc ?
is there a feature you are missing ?
