### ISSUE TITLE
Big x-touch problems

### ISSUE THREAD

**Issue by deltapirat** [xxpasixx/pam-osc#7]
Hi, I'm desperately trying to get the big x-touch to work, but it still doesn't work with your files. I must be doing something wrong. I have followed your instructions exactly, but the faders don't move when I move them with the mouse in the software. Currently Open Stage Control still gives the following error message:
(ERROR, HTTP) Could not setup http server, maybe try a different port ?
Can we discuss this in your discord?

**Comment by xxpasixx** [comment]
we could solve the issue in a DC call.
[https://discord.gg/DxZTZuYZ](https://discord.gg/DxZTZuYZ)
the Port was not configured in OSC and we needed to refresh tehe pages in MA.
