### ISSUE TITLE
Discord Invite Link Invalid

### ISSUE THREAD

**Issue by bootsie123** [xxpasixx/pam-osc#9]
Hi! On the homepage of the wiki it mentions a link to a Discord server however it seems the invite link has expired. If it's still active you might want to update that

Wiki Page: [Home](https://github.com/xxpasixx/pam-osc/wiki)
Referenced Invite Link: [https://discord.gg/DxZTZuYZ](https://discord.gg/DxZTZuYZ)

**Comment by xxpasixx** [comment]
Thanks for pointing that. I updated the link, it should now never expire:
[https://discord.gg/4dcKjTH9Pm](https://discord.gg/4dcKjTH9Pm)

**Comment by bootsie123** [comment]
Sweet. Thank you!
